# Name of the GitHub Actions workflow
name: Deploy Next.js to GitHub Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sets the permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Node.js and caches npm dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a current LTS version
          cache: 'npm'

      # 3. Installs project dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Builds the Next.js application for static export
      - name: Build Next.js site
        run: npm run build
  
      # 5. Configures GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6. Uploads the build output as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The static export is placed in the 'out' folder by default
          path: './out'

      # 7. Deploys the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4